_target_: src.models.vssd.VSSDSegmentation
backbone_kwargs:
    img_size: 512
    patch_size: 16
    out_indices: [0, 1, 2, 3]
    embed_dim: 96
    depths: [3, 4, 21, 5]
    num_heads: [3, 6, 12, 24]
    simple_downsample: False
    simple_patch_embed: False
    ssd_expansion: 2
    ssd_chunk_size: 256
    linear_attn_duality: True
    attn_types: ['mamba2', 'mamba2', 'mamba2', 'standard']
    bidirection: False
    drop_path_rate: 0.6
    use_cpe: True
    ssd_positve_dA: True
decoder_kwargs:
    in_channels: [96, 192, 384, 768]
    pool_scales: [1, 2, 3, 6]
    hidden_size: 512
