train:
  _target_: src.datasets.SidSetDataset
  part: "train:classification"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.SidSetDataset
  part: "val:classification"
  instance_transforms: ${transforms.instance_transforms.inference}
  limit: 12800
